export const DEMO_TOOLS_ENABLED = true;

export const DEMO_TOOLS = [
  {
    toolName: "prometheus",
    tool_name: "prometheus",
    name: "prometheus",
    baseUrl: "http://10.235.21.132:9090",
    base_url: "http://10.235.21.132:9090",
    url: "http://10.235.21.132:9090",
    authToken: null,
    auth_token: null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
  },
  {
    toolName: "grafana",
    tool_name: "grafana",
    name: "grafana",
    baseUrl: "http://10.235.21.132:8080/grafana",
    base_url: "http://10.235.21.132:8080/grafana",
    url: "http://10.235.21.132:8080/grafana",
    authToken: import.meta.env.VITE_DEMO_GRAFANA_TOKEN || null,
    auth_token: import.meta.env.VITE_DEMO_GRAFANA_TOKEN || null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
  },
  {
    toolName: "jaeger",
    tool_name: "jaeger",
    name: "jaeger",
    baseUrl: "http://10.235.21.132:8080/jaeger",
    base_url: "http://10.235.21.132:8080/jaeger",
    url: "http://10.235.21.132:8080/jaeger",
    authToken: null,
    auth_token: null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
  },
  {
    toolName: "opensearch",
    tool_name: "opensearch",
    name: "opensearch",
    baseUrl: "http://10.235.21.132:9200",
    base_url: "http://10.235.21.132:9200",
    url: "http://10.235.21.132:9200",
    authToken: null,
    auth_token: null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
  },
  {
    toolName: "splunk",
    tool_name: "splunk",
    name: "splunk",
    baseUrl: "http://10.235.21.132:8000",
    base_url: "http://10.235.21.132:8000",
    url: "http://10.235.21.132:8000",
    authToken: import.meta.env.VITE_DEMO_SPLUNK_TOKEN || null,
    auth_token: import.meta.env.VITE_DEMO_SPLUNK_TOKEN || null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
  },
  {
    toolName: "alertmanager",
    tool_name: "alertmanager",
    name: "alertmanager",
    baseUrl: "http://10.235.21.132:9093",
    base_url: "http://10.235.21.132:9093",
    url: "http://10.235.21.132:9093",
    authToken: null,
    auth_token: null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
  },
];
