export const DEMO_TOOLS_ENABLED = true;

const HOST = "10.235.21.132";

export const DEMO_TOOLS = [
  {
    id: "demo-prometheus",
    toolName: "prometheus",
    tool_name: "prometheus",
    name: "prometheus",
    baseUrl: `http://${HOST}:9090`,
    base_url: `http://${HOST}:9090`,
    url: `http://${HOST}:9090`,
    authToken: null,
    auth_token: null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
    demo_default: true,
  },
  {
    id: "demo-grafana",
    toolName: "grafana",
    tool_name: "grafana",
    name: "grafana",
    baseUrl: `http://${HOST}:8080/grafana`,
    base_url: `http://${HOST}:8080/grafana`,
    url: `http://${HOST}:8080/grafana`,
    authToken: import.meta.env.VITE_DEMO_GRAFANA_TOKEN || null,
    auth_token: import.meta.env.VITE_DEMO_GRAFANA_TOKEN || null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
    demo_default: true,
  },
  {
    id: "demo-jaeger",
    toolName: "jaeger",
    tool_name: "jaeger",
    name: "jaeger",
    baseUrl: `http://${HOST}:8080/jaeger/ui`,
    base_url: `http://${HOST}:8080/jaeger/ui`,
    url: `http://${HOST}:8080/jaeger/ui`,
    authToken: null,
    auth_token: null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
    demo_default: true,
  },
  {
    id: "demo-opensearch",
    toolName: "opensearch",
    tool_name: "opensearch",
    name: "opensearch",
    baseUrl: `http://${HOST}:9200`,
    base_url: `http://${HOST}:9200`,
    url: `http://${HOST}:9200`,
    authToken: null,
    auth_token: null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
    demo_default: true,
  },
  {
    id: "demo-splunk",
    toolName: "splunk",
    tool_name: "splunk",
    name: "splunk",
    baseUrl: `http://${HOST}:8000`,
    base_url: `http://${HOST}:8000`,
    url: `http://${HOST}:8000`,
    authToken: import.meta.env.VITE_DEMO_SPLUNK_TOKEN || null,
    auth_token: import.meta.env.VITE_DEMO_SPLUNK_TOKEN || null,
    splunk_base_url: `http://${HOST}:8000`,
    splunkBaseUrl: `http://${HOST}:8000`,
    splunk_mgmt_url: `https://${HOST}:8089`,
    splunkMgmtUrl: `https://${HOST}:8089`,
    splunk_hec_url: `http://${HOST}:8088`,
    splunkHecUrl: `http://${HOST}:8088`,
    splunk_hec_token: import.meta.env.VITE_DEMO_SPLUNK_TOKEN || null,
    splunkHecToken: import.meta.env.VITE_DEMO_SPLUNK_TOKEN || null,
    splunk_verify_ssl: false,
    splunkVerifySsl: false,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
    demo_default: true,
  },
  {
    id: "demo-alertmanager",
    toolName: "alertmanager",
    tool_name: "alertmanager",
    name: "alertmanager",
    baseUrl: `http://${HOST}:9093`,
    base_url: `http://${HOST}:9093`,
    url: `http://${HOST}:9093`,
    authToken: null,
    auth_token: null,
    validated: true,
    validation: { reachable: true, demoDefault: true },
    validation_result: { reachable: true, demoDefault: true },
    demo_default: true,
  },
];
